#!/usr/bin/env python3
"""
Generate YAML training configs for Experiment §1 (rank sweep, fixed num_layers=8).

Produces 24 configs: 4 ranks × 3 models × 2 seeds, all targeting age_5_11.

  configs/sweeps/rank{r}_layers8_seed{s}_{model}.yaml
  adapters/sweeps/rank{r}_layers8_seed{s}_{model}_age_5_11/

Usage:
    python scripts/gen_sweep_configs.py             # write all configs
    python scripts/gen_sweep_configs.py --dry-run   # print paths only
"""

import argparse
from pathlib import Path

RANKS      = [2, 4, 8, 16]
SEEDS      = [42, 1337]
MODELS     = {
    "1b":       "mlx-community/Llama-3.2-1B-Instruct-4bit",
    "3b":       "mlx-community/Llama-3.2-3B-Instruct-4bit",
    "qwen4bit": "mlx-community/Qwen2-0.5B-Instruct-4bit",
}

NUM_LAYERS = 8
ROLE       = "age_5_11"

_TMPL = """\
# Experiment §1 rank sweep — auto-generated by scripts/gen_sweep_configs.py
# rank={rank}, num_layers={num_layers}, seed={seed}, model={model_key}
# Do not edit — regenerate with gen_sweep_configs.py

model: "{model_path}"
train: true
fine_tune_type: "lora"
data: "data/{role}"

num_layers: {num_layers}

lora_parameters:
  rank: {rank}
  scale: 20.0
  dropout: 0.0

batch_size: 4
iters: 600
learning_rate: 1e-5

lr_schedule:
  name: cosine_decay
  warmup: 100
  arguments: [1e-5, 600]

mask_prompt: true

adapter_path: "adapters/sweeps/{name}_{role}"

save_every: 100
steps_per_report: 10
steps_per_eval: 60
val_batches: -1
max_seq_length: 768
seed: {seed}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="Print config paths without writing files")
    args = parser.parse_args()

    out_dir = Path("configs/sweeps")
    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    configs = []
    for model_key, model_path in MODELS.items():
        for rank in RANKS:
            for seed in SEEDS:
                name        = f"rank{rank}_layers{NUM_LAYERS}_seed{seed}_{model_key}"
                config_path = out_dir / f"{name}.yaml"
                configs.append((name, config_path, model_key, model_path, rank, seed))

    for name, config_path, model_key, model_path, rank, seed in configs:
        content = _TMPL.format(
            rank=rank,
            num_layers=NUM_LAYERS,
            seed=seed,
            model_key=model_key,
            model_path=model_path,
            role=ROLE,
            name=name,
        )
        if args.dry_run:
            print(f"{config_path}  →  adapters/sweeps/{name}_{ROLE}/")
        else:
            config_path.write_text(content)

    action = "Would generate" if args.dry_run else "Generated"
    print(f"\n{action} {len(configs)} configs.")
    if not args.dry_run:
        print("\nNext steps:")
        print("  bash scripts/setup.sh                          # create adapter dirs")
        print("  bash scripts/train_sweep.sh configs/sweeps/rank4_layers8_seed42_1b.yaml")
        print("  bash scripts/run_sweep_1.sh                    # run all sequentially")


if __name__ == "__main__":
    main()
