#!/usr/bin/env python3
"""
Generate YAML training configs for the Standard-vs-Fast crossover seed campaign.

Motivation: a rank-sweep rerun of the nominal Fast-1B/Fast-3B configuration (same
model, data, seed) produced FK<=7.0 pass rates 12-24 points lower than the original
single run, exceeding the ~8-10pt crossover gap the paper reports. This generates
configs to properly re-test Standard and Fast at both sizes across many seeds so the
crossover can be evaluated with real statistical power instead of n=1 per cell.

Produces configs for: {Standard, Fast} x {1b, 3b} x N seeds, role=age_5_11.

  configs/seed_campaign/{standard,fast}_{model}_seed{s}.yaml
  adapters/seed_campaign/{standard,fast}_{model}_seed{s}_age_5_11/

Reuses existing adapters where a seed/config was already trained under the current
mlx/mlx-lm version (adapters/sweeps/rank4_layers8_seed{42,1337}_{1b,3b}_age_5_11) --
those are referenced directly by the runner script rather than retrained.

Usage:
    python scripts/gen_seed_campaign_configs.py             # write all configs
    python scripts/gen_seed_campaign_configs.py --dry-run   # print paths only
"""

import argparse
from pathlib import Path

# 25 seeds for 1B (faster to train, needed higher N given larger observed noise),
# first 15 of the same list reused for 3B (slower to train, smaller observed noise).
SEEDS_1B = [42, 1337, 7, 123, 256, 512, 777, 999, 2024, 2025,
            3141, 8888, 31415, 55555, 100, 200, 300, 400, 500, 600,
            700, 800, 900, 1000, 1111]
SEEDS_3B = SEEDS_1B[:15]

MODELS = {
    "1b": "mlx-community/Llama-3.2-1B-Instruct-4bit",
    "3b": "mlx-community/Llama-3.2-3B-Instruct-4bit",
}

CONFIGS = {
    "standard": {"rank": 8, "num_layers": 16},
    "fast":     {"rank": 4, "num_layers": 8},
}

ROLE = "age_5_11"

_TMPL = """\
# Seed campaign -- auto-generated by scripts/gen_seed_campaign_configs.py
# config={config_name}, rank={rank}, num_layers={num_layers}, seed={seed}, model={model_key}
# Do not edit -- regenerate with gen_seed_campaign_configs.py

model: "{model_path}"
train: true
fine_tune_type: "lora"
data: "data/{role}"

num_layers: {num_layers}

lora_parameters:
  rank: {rank}
  scale: 20.0
  dropout: 0.0

batch_size: 4
iters: 600
learning_rate: 1e-5

lr_schedule:
  name: cosine_decay
  warmup: 100
  arguments: [1e-5, 600]

mask_prompt: true

adapter_path: "adapters/seed_campaign/{name}_{role}"

save_every: 100
steps_per_report: 10
steps_per_eval: 60
val_batches: -1
max_seq_length: 768
seed: {seed}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="Print config paths without writing files")
    args = parser.parse_args()

    out_dir = Path("configs/seed_campaign")
    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    configs = []
    for model_key, model_path in MODELS.items():
        seeds = SEEDS_1B if model_key == "1b" else SEEDS_3B
        for config_name, params in CONFIGS.items():
            for seed in seeds:
                name = f"{config_name}_{model_key}_seed{seed}"
                config_path = out_dir / f"{name}.yaml"
                content = _TMPL.format(
                    config_name=config_name,
                    rank=params["rank"],
                    num_layers=params["num_layers"],
                    seed=seed,
                    model_key=model_key,
                    model_path=model_path,
                    role=ROLE,
                    name=name,
                )
                configs.append((config_path, content))

    print(f"Generating {len(configs)} configs...")
    for config_path, content in configs:
        if args.dry_run:
            print(config_path)
        else:
            config_path.write_text(content)

    if not args.dry_run:
        print(f"Wrote {len(configs)} configs to {out_dir}/")


if __name__ == "__main__":
    main()
