#!/usr/bin/env python3
"""
Generate YAML training configs for the layer sweep (Experiment §1 optional depth).

Fixes rank=4 and sweeps num_layers ∈ {4, 8, 16} across Llama 1B and 3B,
two seeds each → 12 runs total.

For num_layers=8 the adapter_path points at the existing rank sweep adapters
(adapters/sweeps/rank4_layers8_seed{s}_{model}_age_5_11/) so training is
skipped automatically if run_layer_sweep.sh finds the adapter already present.

Output:
  configs/layer_sweep/rank4_layers{n}_seed{s}_{model}.yaml
  adapters/sweeps/rank4_layers8_seed{s}_{model}_age_5_11/   ← existing, reused
  adapters/layer_sweep/rank4_layers{n}_seed{s}_{model}_age_5_11/  ← new

Usage:
    python scripts/gen_layer_sweep_configs.py
    python scripts/gen_layer_sweep_configs.py --dry-run
"""

import argparse
from pathlib import Path

NUM_LAYERS_VALUES = [4, 8, 16]
SEEDS             = [42, 1337]
RANK              = 4
MODELS            = {
    "1b": "mlx-community/Llama-3.2-1B-Instruct-4bit",
    "3b": "mlx-community/Llama-3.2-3B-Instruct-4bit",
}
ROLE = "age_5_11"

# For num_layers=8, reuse the rank sweep adapters rather than retraining.
_ADAPTER_BASE = {8: "adapters/sweeps"}
_DEFAULT_ADAPTER_BASE = "adapters/layer_sweep"

_TMPL = """\
# Layer sweep — auto-generated by scripts/gen_layer_sweep_configs.py
# rank={rank}, num_layers={num_layers}, seed={seed}, model={model_key}
# Do not edit — regenerate with gen_layer_sweep_configs.py

model: "{model_path}"
train: true
fine_tune_type: "lora"
data: "data/{role}"

num_layers: {num_layers}

lora_parameters:
  rank: {rank}
  scale: 20.0
  dropout: 0.0

batch_size: 4
iters: 600
learning_rate: 1e-5

lr_schedule:
  name: cosine_decay
  warmup: 100
  arguments: [1e-5, 600]

mask_prompt: true

adapter_path: "{adapter_path}"

save_every: 100
steps_per_report: 10
steps_per_eval: 60
val_batches: -1
max_seq_length: 768
seed: {seed}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="Print paths only, do not write files")
    args = parser.parse_args()

    out_dir = Path("configs/layer_sweep")
    if not args.dry_run:
        out_dir.mkdir(parents=True, exist_ok=True)

    configs = []
    for model_key, model_path in MODELS.items():
        for num_layers in NUM_LAYERS_VALUES:
            for seed in SEEDS:
                name = f"rank{RANK}_layers{num_layers}_seed{seed}_{model_key}"
                config_path = out_dir / f"{name}.yaml"
                adapter_base = _ADAPTER_BASE.get(num_layers, _DEFAULT_ADAPTER_BASE)
                adapter_path = f"{adapter_base}/{name}_{ROLE}"
                configs.append((name, config_path, model_key, model_path,
                                 num_layers, seed, adapter_path))

    for name, config_path, model_key, model_path, num_layers, seed, adapter_path in configs:
        reused = num_layers == 8
        content = _TMPL.format(
            rank=RANK,
            num_layers=num_layers,
            seed=seed,
            model_key=model_key,
            model_path=model_path,
            role=ROLE,
            adapter_path=adapter_path,
        )
        tag = " (reuses rank sweep adapter)" if reused else ""
        if args.dry_run:
            print(f"{config_path}  →  {adapter_path}/{tag}")
        else:
            config_path.write_text(content)
            print(f"  {config_path}{tag}")

    action = "Would generate" if args.dry_run else "Generated"
    print(f"\n{action} {len(configs)} configs in configs/layer_sweep/")
    if not args.dry_run:
        print("Next step: bash scripts/run_layer_sweep.sh")


if __name__ == "__main__":
    main()
