#!/usr/bin/env python3
"""
Batch 2: 15 additional seeds for the 3B seed campaign (standard_3b, fast_3b),
bringing each from n=15 to n=30 to get adequate power to test the observed
4.8-point Standard-vs-Fast gap (t=2.01, p=0.054 at n=15/group).

New seeds chosen to not collide with the batch-1 3B seeds already used
(42, 1337, 7, 123, 256, 512, 777, 999, 2024, 2025, 3141, 8888, 31415, 55555, 100).

  configs/seed_campaign/{standard,fast}_3b_seed{s}.yaml
"""

from pathlib import Path

NEW_SEEDS = [200, 300, 400, 500, 600, 700, 800, 900, 1000, 1111,
             4242, 13370, 65537, 271828, 314159]

MODEL_PATH = "mlx-community/Llama-3.2-3B-Instruct-4bit"
CONFIGS = {
    "standard": {"rank": 8, "num_layers": 16},
    "fast":     {"rank": 4, "num_layers": 8},
}
ROLE = "age_5_11"

_TMPL = """\
# Seed campaign batch 2 (3B power top-up) -- auto-generated by scripts/gen_seed_campaign_batch2_3b.py
# config={config_name}, rank={rank}, num_layers={num_layers}, seed={seed}, model=3b
# Do not edit -- regenerate with gen_seed_campaign_batch2_3b.py

model: "{model_path}"
train: true
fine_tune_type: "lora"
data: "data/{role}"

num_layers: {num_layers}

lora_parameters:
  rank: {rank}
  scale: 20.0
  dropout: 0.0

batch_size: 4
iters: 600
learning_rate: 1e-5

lr_schedule:
  name: cosine_decay
  warmup: 100
  arguments: [1e-5, 600]

mask_prompt: true

adapter_path: "adapters/seed_campaign/{name}_{role}"

save_every: 100
steps_per_report: 10
steps_per_eval: 60
val_batches: -1
max_seq_length: 768
seed: {seed}
"""

out_dir = Path("configs/seed_campaign")
out_dir.mkdir(parents=True, exist_ok=True)

count = 0
for config_name, params in CONFIGS.items():
    for seed in NEW_SEEDS:
        name = f"{config_name}_3b_seed{seed}"
        content = _TMPL.format(
            config_name=config_name, rank=params["rank"],
            num_layers=params["num_layers"], seed=seed,
            model_path=MODEL_PATH, role=ROLE, name=name,
        )
        (out_dir / f"{name}.yaml").write_text(content)
        count += 1

print(f"Wrote {count} new configs to {out_dir}/")
